/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'darri' at '10/25/16 11:18 AM' with Gradle 3.1
 *
 * @author darri, @date 10/25/16 11:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
